### ISSUE TITLE
DAS use question

### ISSUE THREAD

**Issue by ilewseu** [anton-jeran/FAST-RIR#2]
Hi, how can I  use DAS to generate RIR conforming to the given RT60?

**Comment by anton-jeran** [comment]
Hi

We cannot control DAS(https://github.com/GAMMA-UMD/pygsound) to generate RIR for a given RT60. Therefore we generate RIR using DAS by varying listener position, speaker position, room dimensions and absorption coefficients. Later we use estimate RT60 of the generated RIR (https://github.com/anton-jeran/FAST-RIR/blob/main/code_new/RT60.py). We use this estimated label to train our network.

**Comment by ilewseu** [comment]
ok，i've got it,thanks very much.
