### ISSUE TITLE
Can not hear the RIR voice

### ISSUE THREAD

**Issue by Tim5Tang** [anton-jeran/FAST-RIR#3]
i have a question, in the web https://anton-jeran.github.io/FRIR/ i can hear the "RIR generated using DAS", but i use your model to generate theRIR-* .wav, i could not hear the voice, how can i check the generated wav is right.

**Comment by anton-jeran** [comment]
Hi,

My model generates the transfer function (Room Impulse Response) to create reverberant speech. You need to convolve the generated RIR using my model with clean speech to simulate reverberant speech. Once you simulate reverberant speech, you can do a listening test to see whether the generated RIRs are right.

Thanks,

Anton

**Comment by JinZr** [comment]
hi anton, 

is there a demo or which script should i use to convolve the generated RIR with clean speech?

thanks!

**Comment by anton-jeran** [comment]
Hi,

You can find the script to convolve clean speech and monoaural RIR here (https://github.com/anton-jeran/FAST-RIR/blob/main/code_new/augment.py).
 
You can follow the steps shown here to augment reverberant speech https://github.com/anton-jeran/MULTI-AUDIODEC/tree/main#single-speaker-binaural-speech.

**Comment by anton-jeran** [comment]
python3 augment.py --speech "clean speech folder" --ir "generated IR folder" --out "output folder" --nthreads 16

**Comment by JinZr** [comment]
dear anton,

thank you so much! i'll look into it!

best
jin
