### ISSUE TITLE
about CPU implementation

### ISSUE THREAD

**Issue by YuyueminAustin** [anton-jeran/FAST-RIR#6]
Is there any available CPU implementation of this work? The paper mentions CPU version but the code is using GPU frequently. Thanks!

**Comment by anton-jeran** [comment]
To run on CPU install pytorch CPU version and set **torch.cuda.set_device** to CPU in relevant places. One place is https://github.com/anton-jeran/FAST-RIR/blob/3e0ec71fea7a5944abc39854861f31fa44765f22/code_new/trainer.py#L53


Also in places with **nn.parallel.data_parallel**.  replace with netG(inputs) https://github.com/anton-jeran/FAST-RIR/blob/3e0ec71fea7a5944abc39854861f31fa44765f22/code_new/trainer.py#L356

You can make sure GPU is not allocated by running nvidia-smi

**Comment by YuyueminAustin** [comment]
thank you very much for the help
